# Generated by Django 2.2.17 on 2022-02-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=128)),
                ('startingLocation', models.CharField(max_length=128)),
                ('productName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128, unique=True)),
                ('baseCost', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
