# Generated by Django 2.2.17 on 2022-02-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=128)),
                ('xPosition', models.IntegerField()),
                ('yPosition', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='CEOName',
            field=models.CharField(default='delfuly', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='startingLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_game.Location'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_game.Product')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business_game.Game'),
            preserve_default=False,
        ),
    ]
